### ISSUE TITLE
docker版Kindle页面无法访问

### ISSUE THREAD

**Issue by somethingwjy** [Suto-Commune/Kindle-Reader-Web-CLI#15]
我的设备是威联通NAS，使用docker-compose创建，以下为docker-compose内容

```
version: '3.2'
services:
  reader:
    container_name: kindle_reader
    image: lolingnatsumi/kindle-reader-web-cli:latest
    network_mode: bridge
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_CACHECHAPTERCONTENT=true
      - READER_APP_SECURE=true 
      - READER_APP_SECUREKEY=ymghtzj
      - READER_APP_INVITECODE=ymghtzj  
    volumes:
      - /share/Container/kindle_reader/logs:/logs 
      - /share/Container/kindle_reader/storage:/storage 
      #- /share/Container/kindle_reader/reader:/reader
    ports:
      - 14444:8080
      - 14450:5000
      - 14410:1000
      - 14480:80
    restart: always
```

我将80,1000,5000,8080端口都做了映射并访问，只有14444:8080访问时能进入web端页面
其余端口访问时浏览器均报错

以下为报错信息

> **Internal Server Error**
> The server encountered an internal error and was unable to complete your request. 
> Either the server is overloaded or there is an error in the application.

以下为报错时产生的日志（使用PC访问了1000和5000端口的端口映射）

> [2023-02-14 13:16:32,324] ERROR in app: Exception on / [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
>     response = self.full_dispatch_request()
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>          ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/reader/head/server.py", line 41, in index
>     main_page["data"].pop(1)
>     ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'str' object has no attribute 'pop'
> 127.0.0.1 - - [2023-02-14 13:16:32] "GET / HTTP/1.1" 500 401 1.829067
> [2023-02-14 13:16:41,049] ERROR in app: Exception on / [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
>     response = self.full_dispatch_request()
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>          ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/reader/head/server.py", line 41, in index
>     main_page["data"].pop(1)
>     ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'str' object has no attribute 'pop'
> 192.168.0.164 - - [2023-02-14 13:16:41] "GET / HTTP/1.1" 500 401 0.015349

若是我配置时有所疏漏导致报错，还望大佬不吝赐教。
感谢您适配kindle，让泡面盖有机会重新发挥余热
